const FRAME_RATE = 60;
const FIELD_WIDTH = 600
const FIELD_HEIGHT = 400
const BALL_RADIUS = 10
const BALL_COLOR = "WHITE"
const BALL_SPEED = 3
const BALL_ACCELERATION = 0.25
const PADDLE_SPEED = 5
const POINTS_TO_WIN = 1000

module.exports = {
  FRAME_RATE,
  FIELD_WIDTH,
  FIELD_HEIGHT,
  BALL_RADIUS,
  BALL_COLOR,
  BALL_SPEED,
  BALL_ACCELERATION,
  PADDLE_SPEED,
  POINTS_TO_WIN,
}